### ISSUE TITLE
Sale Items

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#10]
Why does this item have "on sale from" text 

<img width="290" alt="screen shot 2017-03-23 at 2 53 24 pm" src="https://cloud.githubusercontent.com/assets/3649059/24265027/8d83b77a-0fd8-11e7-8658-fa6a360c5d93.png">

**Comment by JenSparks** [comment]
@GVFTW The collection template shows the price based on a number of conditions and displays this text based on the translation string associated with the price display. 

In this case, because the product has a sales across multiple variants, it show the price as the lowest of those options.

This was always part of the theme and not something we developed.

**Comment by GVFTW** [comment]
@JenSparks got it. can we set it to just display the price from the selected variant like it seems to be doing here?

<img width="320" alt="screen shot 2017-03-30 at 1 59 55 pm" src="https://cloud.githubusercontent.com/assets/3649059/24518868/4a2beb22-1551-11e7-97a2-c3c55dba865d.png">

**Comment by JenSparks** [comment]
@GVFTW No problem--updated!
