### ISSUE TITLE
Filter by Size

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#12]
Per documenation

> 
> In order for products to be included in matching results, the product must have matching tags
> 
> defined in their admin page. The follow tags are supported:

> size_xs
> size_s
> size_m
> size_l
> size_xl

Is it possible to have these associated with the size variants rather than tags? ideally, the filter would reflect what's available vs. what's been tagged.

**Comment by JenSparks** [comment]
@GVFTW 
This isn't easily developed against Shopify's architecture since variants are their own API lookups from their Products.

After some research for automated ways to do this, there are a couple options:
https://apps.shopify.com/instant-search
http://www.nextopia.com

Either would require a monthly SaaS fee and fair amount of customization but you would lose majority of the responsive layouts and features you've designed.

**Comment by GVFTW** [comment]
@JenSparks is there anyway to deconstruct this page to check if they're using tags to manage available sizes? It seems like a lot of maintenance for us -

https://www.outdoorvoices.com/collections/shop-woman

Also, the filter loads super fast and we love the animation.
