### ISSUE TITLE
Thumbnail - Price does not reflect variant Price

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/collection-template#14]
This item is full price but showing on sale - price displayed should be that of selected color variant
<img width="318" alt="screen shot 2017-03-28 at 5 12 06 pm" src="https://cloud.githubusercontent.com/assets/3649059/24427673/d6dda782-13d9-11e7-87af-bad5c5fa6ed2.png">

then on click thru to product page, items shows as full price -
<img width="611" alt="screen shot 2017-03-28 at 5 12 36 pm" src="https://cloud.githubusercontent.com/assets/3649059/24427683/de40b456-13d9-11e7-9635-0cfeb0baf763.png">

**Comment by JenSparks** [comment]
@GVFTW Your hidden open value is the reason the prices show differently. For example, hidden option 3 (style) is different on that variant (F16-PA15) vs the others (S17-PA15).

Can you elaborate what this number is and how it's used? We may be able to help offer some ideas of a better solution for all these price options.

**Comment by GVFTW** [comment]
@JenSparks These are our style numbers and are used to id our products internally, to our vendors and warehouse. S17/F16 is the season, PA15 is the model. The F16 style is on sale, because it's from last season.

We'd just like the price displayed to be that of the selected variant/swatch if possible.

**Comment by JenSparks** [comment]
@GVFTW The comps showed the strike-through price and new prices which is where this started. 

Because you've grouped variants into one product page now, that's when the previous versions showed the price ranges "From $80 - $110". That way shoppers know that the variant they may want could be on the low end or the high end but they'll need to click through to discover.

By showing a single price, the shopper could think that all variants are at that price without ever knowing perhaps their variant is actually different.

We've revised the price logic as you asked. The price on page-load is the minimum price. When a swatch is selected, the price and image change accordingly.
